image: docker:latest
  
variables:
  REPOSITORY_URL_MASTER: <redacted>.dkr.ecr.eu-west-1.amazonaws.com/platform/jenkins
  REPOSITORY_URL_JNLP_SLAVE: <redacted>.dkr.ecr.eu-west-1.amazonaws.com/platform/jenkins-jnlp-slave

services:
  - docker:dind
  
before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli

stages:
  - build

build:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build -f Dockerfile.jnlp-slave -t $REPOSITORY_URL_JNLP_SLAVE .
    - docker push $REPOSITORY_URL_JNLP_SLAVE
    - docker build -t $REPOSITORY_URL_MASTER .
    - docker push $REPOSITORY_URL_MASTER
  only:
    - master
  tags:
    - docker
